version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    networks:
      - dev-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "5001:5000"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
